name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install mtools
      run: sudo apt-get install -y mtools
    - name: Build
      run: ./build.sh
    - name: Get current date
      id: build_date
      run: echo "build_date=$(date +%Y%m%d)" >> $GITHUB_ENV
    - name: Get current commit count
      id: commit_count
      run: echo "commit_count=$(git log --oneline | wc -l)" >> $GITHUB_ENV
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: felix-${{ env.build_date }}-${{ env.commit_count }}
        path: build
