name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install mtools
      run: sudo apt-get install -y mtools
    - name: Build
      run: cargo build --release
    - name: Make build directory
      run: mkdir build
    - name: Objcopy boot
      run: objcopy -I elf32-i386 -O binary target/x86_16-felix/release/felix-boot build/boot.bin
    - name: Objcopy bootloader
      run: objcopy -I elf32-i386 -O binary target/x86_16-felix/release/felix-bootloader build/bootloader.bin
    - name: Objcopy kernel
      run: objcopy -I elf32-i386 -O binary target/x86_16-felix/release/felix-kernel build/kernel.bin
    - name: Create empty floppy image
      run: dd if=/dev/zero of=build/disk.img bs=512 count=2880
    - name: Format floppy
      run: mkfs.fat -F 12 -n "FELIX" build/disk.img
    - name: Put boot
      run: dd if=build/boot.bin of=build/disk.img conv=notrunc
    - name: Put bootloader
      run: dd if=build/bootloader.bin of=build/disk.img bs=512 seek=2816 conv=notrunc
    - name: Copy kernel
      run: mcopy -i build/disk.img build/kernel.bin "::kernel.bin"
    - name: Copy test1.txt
      run: mcopy -i build/disk.img test1.txt "::test1.txt"
    - name: Copy test2.txt
      run: mcopy -i build/disk.img test2.txt "::test2.txt"
    - name: Get current date
      id: build_date
      run: echo "build_date=$(date +%Y%m%d)" >> $GITHUB_ENV
    - name: Get current commit count
      id: commit_count
      run: echo "commit_count=$(git log --oneline | wc -l)" >> $GITHUB_ENV
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: felix-${{ env.build_date }}-${{ env.commit_count }}
        path: build
