name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: cargo build --release
    - name: Make build directory
      run: mkdir build
    - name: Objcopy bootloader
      run: objcopy -I elf32-i386 -O binary target/x86_16-felix/release/felix-bootloader build/boot.bin
    - name: Objcopy kernel
      run: objcopy -I elf32-i386 -O binary target/x86_16-felix/release/felix-kernel build/kernel.bin
    - name: Create empty disk image
      run: dd if=/dev/zero of=build/disk.img bs=512 count=20808 
    - name: Put bootloader
      run: dd if=build/boot.bin of=build/disk.img conv=notrunc
    - name: Put kernel
      run: dd if=build/kernel.bin of=build/disk.img bs=1 seek=512 conv=notrunc
    - name: Get current date
      id: build_date
      run: echo "build_date=$(date +%Y%m%d)" >> $GITHUB_ENV
    - name: Get current commit count
      id: commit_count
      run: echo "commit_count=$(git log --oneline | wc -l)" >> $GITHUB_ENV
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: felix-${{ env.build_date }}-${{ env.commit_count }}
        path: build
